version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    networks:
      - web
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    image: php:7.2.2-apache
    container_name: php_web
    volumes:
      - ./html/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php
    links:
      - db
    networks:
      - web
    restart: always


# Docker Volumes
volumes:
  mysql_data:
    driver: local
  
# Docker Networks
networks:
  web:
    driver: bridge
    