FROM php:7.2.2-apache

# Setting apache conf files
COPY conf/pessoal.conf   /etc/apache2/sites-available/
COPY conf/aa.conf        /etc/apache2/sites-available/

# Updating docker image repository
RUN apt-get update 

# Installing PHP-PDO-MySQL Driver
RUN docker-php-ext-install pdo pdo_mysql mysqli && \
    docker-php-ext-enable mysqli

# Installing PHP modules
RUN apt-get install -y libpng-dev && \
    docker-php-ext-install mbstring && \
    docker-php-ext-install zip && \ 
    docker-php-ext-install gd && \
    docker-php-ext-install opcache

# Enabling URL rewrite module and setting .conf apache file
RUN a2enmod rewrite && \
    a2dissite 000-default.conf && \
    a2ensite pessoal.conf && \
    a2ensite aa.conf

# Version
# ENV COMPOSER_VERSION 1.8.5

# Installing Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Installing Sass
COPY dart-sass.tar.gz /tmp/
RUN tar -xvf /tmp/dart-sass.tar.gz -C /opt/ && \
    echo "export PATH='/opt/dart-sass/:$PATH'" >> ~/.bashrc &&\
    rm /tmp/dart-sass.tar.gz

# Installing Git, Zip, Vi, Sendmail and libpng
RUN apt-get install -y git && \
    apt-get install -y zip && \
    apt-get install -y vim && \
    apt-get install -y libpng-dev

# Installing Drupal Console and Drush Launcher 
RUN curl https://drupalconsole.com/installer -L -o drupal.phar && \
    mv drupal.phar /usr/local/bin/drupal && \
    chmod +x /usr/local/bin/drupal && \
    curl https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar -L -o drush.phar && \
    mv drush.phar /usr/local/bin/drush && \
    chmod +x /usr/local/bin/drush


# Setting working dir at interact mode
WORKDIR /var/www/html

# Exposing 3306 (mysql) port
EXPOSE 3306
