FROM php:7.2.2-apache

# Setting apache conf files
COPY conf/pessoal.conf   /etc/apache2/sites-available/
COPY conf/aa.conf        /etc/apache2/sites-available/

# Installing PHP-Pdo-mysql Driver
RUN docker-php-ext-install pdo pdo_mysql

# Enabling URL rewrite module and setting .conf apache file
RUN a2enmod rewrite
RUN a2dissite 000-default.conf
RUN a2ensite pessoal.conf
RUN a2ensite aa.conf

# Version
ENV COMPOSER_VERSION 1.8.5

# Installing Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Installing Sass
COPY dart-sass.tar.gz /opt/
WORKDIR /opt/
RUN tar -xvf dart-sass.tar.gz
# ENV PATH=/opt/dart-sass/:$PATH
RUN echo "export PATH='/opt/dart-sass/:$PATH'" >> ~/.bashrc

# Installing Git
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install -y zip && \
    apt-get install -y vim

WORKDIR /var/www/html